### ISSUE TITLE
archive all repositories?

### ISSUE THREAD

**Issue by josharian** [card-io/card.io-iOS-source#104]
I propose that we archive all card.io repositories: https://help.github.com/articles/about-archiving-repositories/

I believe that this would simply accurately reflect the state of affairs that has already been in place for quite some time.

Any objections, @dgoldman-pdx or @burnto or anyone else?

**Comment by dgoldman-pdx** [comment]
That certainly seems appropriate. Alas.

**Comment by burnto** [comment]
:shipit:

**Comment by josharian** [comment]
Thanks. Done.
