### ISSUE TITLE
card.io dmz: Expiry segmentation failed.

### ISSUE THREAD

**Issue by eamitg** [card-io/card.io-iOS-source#13]
Hi again,

I keep getting it while scanning the card and currently unable to complete card scanning using the sources.

Regards

**Comment by dgoldman-ebay** [comment]
"Expiry segmentation failed" means that the expiry-scanning code was unable to locate the expiration date on the card. In such cases, the code will nevertheless continue to try to find and identify the *card number*, and if it can do so will return successfully (even without the expiry).

The reasons for failure to locate the expiration date include: poor contrast between the expiry digits and the card's background, poor lighting, unexpected expiry formats, etc.
