### ISSUE TITLE
can't release

### ISSUE THREAD

**Issue by springlo** [card-io/card.io-iOS-source#14]
when I run  fab build:outdir=~ 
Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/lc
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty

Fatal error: local() encountered an error (return code 128) while executing 'git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty'

Aborting.

how can I do?

**Comment by dgoldman-ebay** [comment]
@springlo try entering that `git describe...` command directly on the command line yourself. Hopefully this will produce a more detailed error message that will help point to the source of the problem.

**Comment by springlo** [comment]
Now,it's print:

Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/lc
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty
Preparing dmz

Fatal error: local() encountered an error (return code 1) while executing 'fab concat'

Aborting.

**Comment by dgoldman-ebay** [comment]
Wait -- how did you get past the first error? What did you change?

**Comment by springlo** [comment]
May be what I am doing wrong。Forget it, I'll pack manually using xcode。
Thx, @dgoldman-ebay 。

**Comment by sachin123sharma** [comment]
I am facing same issue ? Please suggest .getting following error

-source-master ssharma$ fab build:outdir=~
[localhost] local: xcode-select -p
Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/ssharma
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty

Fatal error: local() encountered an error (return code 128) while executing 'git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty'

Aborting.
