### ISSUE TITLE
How can i integrate card.io without scan card feature(only manual entry) with custom UI 

### ISSUE THREAD

**Issue by mihirpmehta** [card-io/card.io-iOS-source#15]
First of all thanks for the wonderful library. 
In one of my app i want to use card.io's mechanism to validate the card , but i do not want scanning feature I only want manual entry feature.

And also i have my custom UI built in for getting card's number and expiry.

Can i apply your your method to validate those info along with displaying card's image on the textfiled alon with the formatter (i.e. 4111 1111 1111 111) ?

Thanks

**Comment by dgoldman-ebay** [comment]
@mihirpmehta it sounds like you will want to simply copy a few bits of code from our project.

From the [card.io-dmz](https://github.com/card-io/card.io-dmz) repo, you might want `dmz_card_info_for_prefix_and_length()` and `dmz_passes_luhn_checksum()` (both in [`dmz-olm.h`](https://github.com/card-io/card.io-dmz/blob/master/dmz_olm.h).)

From the [card.io-iOS-source](https://github.com/card-io/card.io-iOS-source) repo, some of the code from, for example, [CardIONumbersTextFieldDelegate.m](https://github.com/card-io/card.io-iOS-source/blob/master/Classes/CardIONumbersTextFieldDelegate.m) might be helpful.

Just be sure to include with any copied code our [copyright and license text](https://github.com/card-io/card.io-iOS-source/blob/master/LICENSE.md).
