### ISSUE TITLE
Card.IO locks the focus 

### ISSUE THREAD

**Issue by junaidabidi** [card-io/card.io-iOS-source#17]
Card.IO locks the focus and does not unlock it after use. This throws up issues when using other libraries - i am using Jumio Netverify to OCR identity documents. After using Card.IO in the same cordova app, Jumio SDK is unable to focus properly. 

Could you please pinpoint where the issue is and how we reset the focus and other setting to default values? 

I am happy to fix and create a pull request ..

Many thanks,
Junaid

**Comment by junaidabidi** [comment]
Ok, so i have figured it out. I am forcing focus settings of the device after card read to get Jumio SDK to work . 

```
  NSError *error = nil;
    //Set the device setting back to default - Bug in Jumio library which
    AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo];
    
    if ([device respondsToSelector:@selector(isAutoFocusRangeRestrictionSupported)]
        && device.autoFocusRangeRestrictionSupported
        && [device lockForConfiguration:&error]) {
        [device setAutoFocusRangeRestriction:AVCaptureAutoFocusRangeRestrictionNone];
        [device unlockForConfiguration];
    }
```

**Comment by dgoldman-ebay** [comment]
Thanks, @junaidabidi!

So your suggestion is that card.io should include essentially the above code when it is finished with the camera?

**Comment by junaidabidi** [comment]
Yeah, it will be great to leave the setting to default value as other libraries might assume the camera to be in default state (ideally they should initialise it properly but there you go ).

**Comment by dgoldman-ebay** [comment]
Now officially [released](https://github.com/card-io/card.io-iOS-SDK/releases)
