### ISSUE TITLE
Getting error when running fab build:outdir=~

### ISSUE THREAD

**Issue by Thavasidurai** [card-io/card.io-iOS-source#18]
First of all thanks for this wonderful library!
I did some changes in the source code so I tried to build the code by following the steps you mentioned in the Github page. After installing python and fabric I just i ran the fab build:outdir=~ comment. It started to build but suddenly it aborted. Can you please guide me what is the mistake I did here? and also it would be really good if you provide some detailed steps for unofficial card.io-iOS-SDK release. It may help us people like me those who has only objective-c knowledge.

Below is the output i got when ran fab build:outdir=~ comment

thavasi-2473:card.io-iOS-source thavasi-2473$ fab build:outdir=~
Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/thavasi-2473
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty
Preparing dmz
Building
Using temp dir /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/
Using extra Xcode flags: 
(Release) Building armv7
(Release) Building armv7s
(Release) Building arm64
(Release) Building i386
(Release) Building x86_64
(Release) Lipoing

Fatal error: local() encountered an error (return code 127) while executing '`xcode-select -print-path`/Platforms/iPhoneOS.platform/Developer/usr/bin/lipo            /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/armv7/libCardIO.a           -arch armv7s /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/armv7s/libCardIO.a           -arch arm64 /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/arm64/libCardIO.a           -arch i386 /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/i386/libCardIO.a           -arch x86_64 /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/x86_64/libCardIO.a           -create           -output /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/universal/libCardIO.a'

Aborting.
local() encountered an error (return code 127) while executing '`xcode-select -print-path`/Platforms/iPhoneOS.platform/Developer/usr/bin/lipo            /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/armv7/libCardIO.a           -arch armv7s /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/armv7s/libCardIO.a           -arch arm64 /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/arm64/libCardIO.a           -arch i386 /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/i386/libCardIO.a           -arch x86_64 /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/x86_64/libCardIO.a           -create           -output /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmp2efPDO/Release/universal/libCardIO.a'
thavasi-2473:card.io-iOS-source thavasi-2473$

**Comment by josharian** [comment]
If you run `xcode-select -print-path` in your terminal, what does it say?

**Comment by Thavasidurai** [comment]
if I run xcode-select -print-path in my terminal then it says /Applications/Xcode 3.app/Contents/Developer

**Comment by dgoldman-ebay** [comment]
@Thavasidurai if you're really still running Xcode 3, then the first thing I'd suggest is that you update to the current version, [Xcode 6.2](https://developer.apple.com/xcode/downloads/).

(Perhaps you can get that done, and report back on whether that has changed your results, prior to @josharian waking up and resuming the conversation. :smiley_cat:)

**Comment by Thavasidurai** [comment]
No, I am running Xcode 6.1

**Comment by dgoldman-ebay** [comment]
In that case, it looks like either you have renamed the Xcode app to `Xcode 3`, or (rather more likely) you still have a copy of Xcode 3 somewhere on your computer.

Back in the days of Xcode 3, Apple placed utility programs such as `lipo` in a different place than they do now. I think that your error message was caused by the script failing to find `lipo` where it expects it to be; namely, inside the Xcode app package. But it was looking inside your old Xcode 3, rather than inside Xcode 6.1.

So if you delete from your computer all old copies of Xcode, I think that things will improve.

**Comment by Thavasidurai** [comment]
Thank you so much :-) I follow your comments and come back here if i face any issue.

**Comment by Thavasidurai** [comment]
I didn't have any old xcode version in my computer. Actually my xcode 6.1 was named as xcode 3. Now I renamed it to xcode but it seems still some issues are there. Below is the issue which terminal says

thavasi-2473:~ thavasi-2473$ cd /Users/thavasi-2473/card.io-iOS-source 
thavasi-2473:card.io-iOS-source thavasi-2473$ fab build:outdir=~
Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/thavasi-2473
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty
Preparing dmz
Building
Using temp dir /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmpW36QFj/
Using extra Xcode flags: 
(Release) Building armv7

Fatal error: local() encountered an error (return code 1) while executing 'xcrun xcodebuild -target CardIO -arch armv7 -sdk iphoneos -configuration Release clean'

Aborting.
local() encountered an error (return code 1) while executing 'xcrun xcodebuild -target CardIO -arch armv7 -sdk iphoneos -configuration Release clean'
thavasi-2473:card.io-iOS-source thavasi-2473$

Can you please help me out on this?

**Comment by dgoldman-ebay** [comment]
Rather than running `fab build:outdir=~`, try `fab verbose build:outdir=~`

This will result in a *much* larger output. It will include the specific Xcode compiler or linker errors that are causing the build to fail.

**Comment by Thavasidurai** [comment]
Thank you so much for your quick response!

Below is the response for fab verbose build:outdir=~ 

thavasi-2473:card.io-iOS-source thavasi-2473$ fab verbose build:outdir=~
Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/thavasi-2473
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty
[localhost] local: git rev-parse --show-toplevel
Preparing dmz
[localhost] local: fab concat

Done.
Building
Using temp dir /var/folders/qc/chpg1l0x09l2fphydw9rjw88xjk2sw/T/tmprWu6A8/
Using extra Xcode flags: 
(Release) Building armv7
[localhost] local: xcrun xcodebuild -target CardIO -arch armv7 -sdk iphoneos -configuration Release clean
xcrun: error: active developer path ("/Applications/Xcode 3.app/Contents/Developer") does not exist, use `xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools (or see `man xcode-select`)

Fatal error: local() encountered an error (return code 1) while executing 'xcrun xcodebuild -target CardIO -arch armv7 -sdk iphoneos -configuration Release clean'

Aborting.
local() encountered an error (return code 1) while executing 'xcrun xcodebuild -target CardIO -arch armv7 -sdk iphoneos -configuration Release clean'

I don't have anything like xcode 3 in my computer but still its seeking at ("/Applications/Xcode 3.app/Contents/Developer") seems.

**Comment by Thavasidurai** [comment]
Thank you so much for your support!

I used xcode-select --switch /Applications/Xcode.app/Contents/Developer
          Select   /Applications/Xcode.app/Contents/Developer comment to set the active developer directory then fab build:outdir=~ comment was worked without any issues.

**Comment by dgoldman-ebay** [comment]
Awesome! Glad you got it working, @Thavasidurai!

**Comment by sachin123sharma** [comment]
Also I am getting following Error while running using Fab Command to build library
ServiceMasterssharma:card.io-iOS-source-master ssharma$ fab verbose build:outdir=~
[localhost] local: xcode-select -p
Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/ssharma
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty

Fatal error: local() encountered an error (return code 128) while executing 'git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty'

Aborting.

**Comment by sachin123sharma** [comment]
To resolve above issue , I set up project using git , than i was able to compile ,but archiving failing with following error .

In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/Classes/CardIOPaymentViewController.m:18:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/cv/warp.h:10:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/dmz.h:11:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/scan.h:9:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/frame.h:9:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/expiry_seg.h:9:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/expiry_types.h:10:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/eigen.h:25:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/Eigen/Core:20:
/Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/Eigen/src/Core/util/Macros.h:248:1: error: unknown type name 'namespace'
namespace Eigen {
^
/Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/Eigen/src/Core/util/Macros.h:248:16: error: expected ';' after top level declarator
namespace Eigen {
               ^
               ;
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/Classes/CardIOPaymentViewController.m:18:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/cv/warp.h:10:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/dmz.h:11:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/scan.h:9:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/frame.h:9:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/expiry_seg.h:9:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/scan/expiry_types.h:10:
In file included from /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/eigen.h:25:
/Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz/Eigen/Core:28:10: fatal error: 'complex' file not found
#include <complex>
         ^
3 errors generated.

CompileC /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOGuideLayer.o Classes/CardIOGuideLayer.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/ssharma/.rvm/gems/ruby-2.3.0/bin:/Users/ssharma/.rvm/gems/ruby-2.3.0@global/bin:/Users/ssharma/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ssharma/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -arch arm64 -fmessage-length=176 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -stdlib=libc++ -fobjc-arc -gmodules -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -DCARDIO_DEBUG=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -miphoneos-version-min=6.0 -g -Wno-sign-conversion -fembed-bitcode -iquote /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-generated-files.hmap -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-own-target-headers.hmap -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-all-target-headers.hmap -iquote /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-project-headers.hmap -I/var/folders/lk/knb6cbxs2352gy3fc6g53jwwf__ncs/T/tmpBT31tB/Release/Archive/include -I/Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/opencv_device/include -I/Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/DerivedSources/arm64 -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/DerivedSources -F/var/folders/lk/knb6cbxs2352gy3fc6g53jwwf__ncs/T/tmpBT31tB/Release/Archive -include /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/PrecompiledHeaders/CardIO-Prefix-aisczoqlcbknkvfzqxldmomcgagf/CardIO-Prefix.pch -MMD -MT dependencies -MF /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOGuideLayer.d --serialize-diagnostics /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOGuideLayer.dia -c /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/Classes/CardIOGuideLayer.mm -o /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOGuideLayer.o

CompileC /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOIplImage.o Classes/CardIOIplImage.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/ssharma/.rvm/gems/ruby-2.3.0/bin:/Users/ssharma/.rvm/gems/ruby-2.3.0@global/bin:/Users/ssharma/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ssharma/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -arch arm64 -fmessage-length=176 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -stdlib=libc++ -fobjc-arc -gmodules -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -DCARDIO_DEBUG=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -miphoneos-version-min=6.0 -g -Wno-sign-conversion -fembed-bitcode -iquote /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-generated-files.hmap -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-own-target-headers.hmap -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-all-target-headers.hmap -iquote /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/CardIO-project-headers.hmap -I/var/folders/lk/knb6cbxs2352gy3fc6g53jwwf__ncs/T/tmpBT31tB/Release/Archive/include -I/Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/opencv_device/include -I/Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/dmz -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/DerivedSources/arm64 -I/Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/DerivedSources -F/var/folders/lk/knb6cbxs2352gy3fc6g53jwwf__ncs/T/tmpBT31tB/Release/Archive -include /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/PrecompiledHeaders/CardIO-Prefix-aisczoqlcbknkvfzqxldmomcgagf/CardIO-Prefix.pch -MMD -MT dependencies -MF /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOIplImage.d --serialize-diagnostics /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOIplImage.dia -c /Users/ssharma/Desktop/ServiceMaster/Project/CARDIO/August/GIT_SOURCE/card.io-iOS-source/Classes/CardIOIplImage.mm -o /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOIplImage.o

** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/ssharma/Library/Developer/Xcode/DerivedData/icc-gibrpkkvyhxegjezojxuyjwygsmj/Build/Intermediates/ArchiveIntermediates/CardIO\ Static\ Library/IntermediateBuildFilesPath/icc.build/Release-iphoneos/CardIO-static.build/Objects-normal/arm64/CardIOPaymentViewController.o Classes/CardIOPaymentViewController.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Fatal error: local() encountered an error (return code 65) while executing 'xcrun xcodebuild -scheme "CardIO Static Library" -target CardIO-static -configuration Release archive  CONFIGURATION_BUILD_DIR=/var/folders/lk/knb6cbxs2352gy3fc6g53jwwf__ncs/T/tmpBT31tB/Release/Archive  GCC_PREPROCESSOR_DEFINITIONS='$(value) ''

Please suggest?

**Comment by romk1n** [comment]
@sachin123sharma did you run `git submodule update --init` ? if that doesn't help please open a new issue

**Comment by sachin123sharma** [comment]
Thanks , That works.
