### ISSUE TITLE
How to open scan camera screen using Paypal SDK

### ISSUE THREAD

**Issue by dharmikvyas** [card-io/card.io-iOS-source#19]
Hello,
I have used card io lib, that works fine. Now I need to use Paypal in my app. 
SO I have to remove card io lib.
Is there any method to open camera screen to scan, like card io does, Using Paypal?

**Comment by dgoldman-ebay** [comment]
@dharmikvyas if you use the [PayPal iOS SDK](https://github.com/paypal/PayPal-iOS-SDK), you will get card.io scanning automatically.

If you are having problems with this, please open an issue in the [PayPal iOS SDK](https://github.com/paypal/PayPal-iOS-SDK) repository.

**Comment by dgoldman-ebay** [comment]
Glad [you worked it out](https://github.com/paypal/PayPal-iOS-SDK/issues/264), @dharmikvyas!
