### ISSUE TITLE
resolution is low, let user specify the sessionPreset?

### ISSUE THREAD

**Issue by kevin-zqw** [card-io/card.io-iOS-source#20]
`#define kCaptureSessionDefaultPresetResolution AVCaptureSessionPreset640x480`

`// If we ever want to use higher resolution images, this is a good place to do that.`
`//    if ([self.captureSession canSetSessionPreset:AVCaptureSessionPreset1920x1080]) {`
`//      self.captureSession.sessionPreset = AVCaptureSessionPreset1920x1080;`
`//    }`
`//    else`
`//    if ([self.captureSession canSetSessionPreset:AVCaptureSessionPreset1280x720]) {`
`//      self.captureSession.sessionPreset = AVCaptureSessionPreset1280x720;`
`//    }`
`//  }`

`[self.captureSession addInput:self.cameraInput];`
`self.captureSession.sessionPreset = kCaptureSessionDefaultPresetResolution;`

Should I turn these parts of code into a public interface?

**Comment by josharian** [comment]
It's not just a question of asking the camera to generate higher resolution images. We need to also be prepared to process them downstream. If I recall correctly, we are not. (Give it a try and find out, if you're interested.)

**Comment by dgoldman-ebay** [comment]
@josharian is correct. For a much more detailed explanation, see this [comment from March 3](https://github.com/card-io/card.io-iOS-source/issues/16#issuecomment-77111035).
