### ISSUE TITLE
how to build up static library from this source code?

### ISSUE THREAD

**Issue by lanzhiyuan** [card-io/card.io-iOS-source#23]
I'm newer,please tell me step by step,thx!

**Comment by dgoldman-ebay** [comment]
@lanzhiyuan this is a standard Xcode project. Simply open the project file, `icc.xcodeproj`, and build the `icc` or `CardIO` target.

I'm sorry, but we don't have the resources to explain all the step-by-step details. If you have done any significant amount of iOS development, then the above should suffice.

**Comment by lanzhiyuan** [comment]
@dgoldman-ebay thanks for your instruction, I never build up static library like this. As you said, I build icc.xcodeproj,there're some error issues,warp.h file not found, dmz.h file not found.where can I get them?
'git submodule sync' and 'git submodule update' didn't make any change, I still have no source of dmz.Thank you so much！

**Comment by dgoldman-ebay** [comment]
@lanzhiyuan try `git submodule update --recursive`
