### ISSUE TITLE
i cant scan the card number without steel seal

### ISSUE THREAD

**Issue by sparkdreamstudio** [card-io/card.io-iOS-source#24]
![c6af74da-549f-4c82-a412-6110e9484c16](https://cloud.githubusercontent.com/assets/1477665/7997920/77e21c94-0b67-11e5-88af-b64bc97d324e.png)

**Comment by sparkdreamstudio** [comment]
if it because of the card has 19 number?

**Comment by dgoldman-ebay** [comment]
@sparkdreamstudio I do not understand what you mean by "steel seal".

But yes, if this card has 19 digits that would partially explain your problem.

card.io is designed to scan traditional embossed cards (which yours is not), of these 5 types: MasterCard, VISA, AmEx, Discover, JCB (which yours is not).
