### ISSUE TITLE
proposal: way to reduce visual glitches of buttons on screen rotation

### ISSUE THREAD

**Issue by mcyril** [card-io/card.io-iOS-source#30]
in CardIOViewController.mm, block of lines between 318 and 334 which normalizes buttons sizes, could be framed with 
```
    [CATransaction begin];
    [CATransaction setDisableActions:YES];
//...
    [CATransaction commit];
```
code to reduce visual glitches of buttons on screen rotation. it works for deltas InterfaceToDeviceOrientationRotatedClockwise and InterfaceToDeviceOrientationRotatedCounterclockwise. for deltas InterfaceToDeviceOrientationSame and InterfaceToDeviceOrientationUpsideDown it's better to omit mentioned framing.

**Comment by dgoldman-ebay** [comment]
Thanks for the suggestion, @mcyril! This makes sense, and explains what was previously confusing me in that section of code.

I'm still not clear why we want to do this only for certain rotations, but for now I'd rather implement what observably works than spend more time trying to understand these fine points.

**Comment by dgoldman-ebay** [comment]
Incorporated in [Version 5.1.0](https://github.com/card-io/card.io-iOS-SDK/releases).

**Comment by mcyril** [comment]
I realized it after several experiments and the bypassing of CoreAnimation disable for InterfaceToDeviceOrientationSame and InterfaceToDeviceOrientationUpsideDown deltas is lesser evil. maybe one day there will be found a better solution.

and thank you for new release!
