### ISSUE TITLE
CardDetectionMode

### ISSUE THREAD

**Issue by rishigoel** [card-io/card.io-iOS-source#44]
If I set the card detection mode to image only, is there an internal function that would allow me to perform OCR on the image or would I have to use another API like tesseract?  I'm using a Manulife Bank card so the number can't be recognized.

**Comment by dgoldman-ebay** [comment]
@rishigoel the OCR functions inside the card.io library work only on single, isolated digits. So you would first need to do the very challenging work of locating each of those digits.

Therefore yes, you'd need some other API to locate and parse the relevant numbers.
