### ISSUE TITLE
#import "dmz.h"

### ISSUE THREAD

**Issue by mengmanzbh** [card-io/card.io-iOS-source#46]
dmz.h file not found

**Comment by bluk** [comment]
Please see the [instructions](https://github.com/card-io/card.io-iOS-source#dev-setup). You probably need to initialize the git submodules via `git submodule sync; git submodule update --init --recursive`.

**Comment by mengmanzbh** [comment]
Submodule 'dmz' (git@github.com:card-io/card.io-dmz.git) registered for path 'dmz'
Cloning into 'dmz'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:card-io/card.io-dmz.git' into submodule path 'dmz' failed
localhost:card.io-iOS-source kuailefu$

**Comment by mengmanzbh** [comment]
git submodule update --init --recursive  

localhost:card.io-iOS-source kuailefu$ git submodule update --init --recursive
Cloning into 'dmz'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:card-io/card.io-dmz.git' into submodule path 'dmz' failed
localhost:card.io-iOS-source kuailefu$

**Comment by bluk** [comment]
In the card.io source directory in can you edit your `.git/config`file and change the following part:
```
[submodule "dmz"]
        url = https://github.com/card-io/card.io-dmz.git
```
The URL can point to the `https` clone location instead of the `ssh/git://` one.

**Comment by mengmanzbh** [comment]
success. thanks

**Comment by mengmanzbh** [comment]
Ask a question if the card is not a credit card, can scan it?

**Comment by dgoldman-ebay** [comment]
@mengmanzbh The code is currently tightly tied to scanning credit cards (just the 5 supported types: MasterCard, Visa, American Express, Discover, JCB). Adding additional types of credit cards or non-credit cards would be great, but will require a LOT of work.

**Comment by bluk** [comment]
I believe this question was answered, but if not, please reopen or leave a comment. Thanks.

**Comment by PuzzleVerse** [comment]
I have added support for union pay scanning but now I cannot get the ref of the changes from my fork.

Getting the following error when I want to init the submodule from another location : 
error: no such remote ref 7ec265ef8ee4a0a439483d603117e0ff440bddf8
Fetched in submodule path 'dmz', but it did not contain 7ec265ef8ee4a0a439483d603117e0ff440bddf8. Direct fetching of that commit failed.

Any Ideas ?
