### ISSUE TITLE
git submodule update --init --recursive

### ISSUE THREAD

**Issue by mengmanzbh** [card-io/card.io-iOS-source#48]
Submodule 'dmz' (git@github.com:card-io/card.io-dmz.git) registered for path 'dmz'
Cloning into 'dmz'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:card-io/card.io-dmz.git' into submodule path 'dmz' failed
localhost:card.io-iOS-source kuailefu$

**Comment by dgoldman-ebay** [comment]
@mengmanzbh please stop opening multiple issues to discuss one problem.

Conversation continues in your original issue, #46.
