### ISSUE TITLE
Unable to identify the card number

### ISSUE THREAD

**Issue by ReizSoon** [card-io/card.io-iOS-source#54]
thank you share，i have a problem, unable to identify the card number,like this image ,http://img.dragonpass.com.cn/uploadFile/share/20151228/3de88043-3344-4623-8972-7094e04c4cc6.jpg  please help!

**Comment by dgoldman-ebay** [comment]
@ReizSoon The card.io library is specifically designed to recognize credit cards (MasterCard, VISA, AmEx, Discover, JCB). Your DragonPass card is not one of these credit cards.

**Comment by ReizSoon** [comment]
How to change to support  my DragonPass card，thank you

**Comment by dgoldman-ebay** [comment]
@ReizSoon Please read the discussions in [the other issues](https://github.com/card-io/card.io-iOS-source/issues?q=is%3Aissue) for this repository. You will learn that there is no simple answer to your question.
