### ISSUE TITLE
Carthage compatibility.

### ISSUE THREAD

**Issue by Dershowitz011** [card-io/card.io-iOS-source#68]
Carthage support not working on xcode 8 beta 3. Please fix it. The log is here:

```
*** Fetching card.io-iOS-source
*** Checking out card.io-iOS-source at "iOS_5.3.2"
A shell task (/usr/bin/env git clone --quiet git@github.com:card-io/card.io-dmz.git%
```

**Comment by Dershowitz011** [comment]
Help please?

**Comment by bluk** [comment]
@Dershowitz011 As noted in https://github.com/paypal/PayPal-iOS-SDK/issues/438 , please try adding a [SSH key to your GitHub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).

**Comment by Dershowitz011** [comment]
I will try and get back. Kindly hold on.

**Comment by bluk** [comment]
Seems you are able to checkout and build successfully in paypal/PayPal-iOS-SDK#438 so closing this issue.
