### ISSUE TITLE
Finnish localization is still not working

### ISSUE THREAD

**Issue by JussiSuojanen** [card-io/card.io-iOS-source#88]
### General information

* SDK/Library version: 5.4.1
* iOS Version and Device: iOS 10.2.1 iPhone7
* Integration type and version:  CocoaPods 1.1.2

### Issue description

Finnish localization is still not working. I can only see english texts if device language is set to Finnish.

I made a  ["fix"](https://github.com/card-io/card.io-iOS-source/pull/77) for this 6 months ago but it seems that it does not fix the issue. I thought, maybe you just haven't yet released it and tried make my own release in my [fork](https://github.com/JussiSuojanen/card.io-iOS-SDK)  but sadly the result is the same.

Any idea what is the problem? I tried to compare the commit I made PR from, to another localization commit but could not spot the difference. I'd really appreciate if you could help me.

Thanks,
Jussi

**Comment by josharian** [comment]
I'm seriously out of touch with card.io at this point, but at least at some point in the past, all localization files got converted into code used baler, so that card.io could distribute a single binary without extra assets. Perhaps that's what went wrong? Just a guess.

**Comment by JussiSuojanen** [comment]
I followed official [release guide](https://github.com/card-io/card.io-iOS-source/blob/master/official_release.md) and it uses fab to build the project. Never used the baler before, I'll look into that I just don't have time to do it the start of this week. If it does not help, where should I look next? :)

I also have a request to add 3-4 Baltian languages to card.io SDK so it would be great to get this working.

**Comment by JussiSuojanen** [comment]
Finally had the time to test baler to build the resources and it worked! Thanks Josharian for the info. Btw, Baler is not mentioned in the official release guide as a step to build the resources and I think it should be added there.

This issue can now be closed.
