### ISSUE TITLE
CardIOPaymentViewController.m:24:11: fatal error: 'CardIOBundle.h' file not found

### ISSUE THREAD

**Issue by ricardolpd** [card-io/card.io-iOS-source#9]
Hello,

First off all apologies for posting here in the issues, but i couldn't find anywhere to ask for help (do you guys/girls have a discussion place for card.io?). I have pulled the card.ios-Source, and in my project both these files are missing 'CardIOBundle.h' and 'CardIOBundle.m'. 

I noticed that these two files are part of the .gitignore file, which leads me to believe they should be auto-generated. How do I do this? What am I missing?

Many thanks

**Comment by dgoldman-ebay** [comment]
@ricardolpd Thanks for your very timely posting!

Those two `CardIOBundle` files are indeed auto-generated, from the strings and graphic assets in the project. We use [Baler](https://github.com/paypal/baler) to package these assets as code (since an iOS library can not include its own resources). (Yes, under iOS 8 a *framework* can do so, but we still support earlier versions of iOS.)

Prior to this morning, you would have received a build error regarding not having [installed Baler](https://github.com/card-io/card.io-iOS-source#baler). But a commit earlier today removed that requirement.

Which means that we now need to remove those files from `.gitignore`. Which I've just now done. Should work much better for you now! :smirk:

**Comment by dgoldman-ebay** [comment]
P.S. Posting here in the Issues is precisely correct. :smile_cat:

**Comment by ricardolpd** [comment]
Thank you so much @dgoldman-ebay. Question do you guys a have place to discuss stupid newbie questions?

**Comment by dgoldman-ebay** [comment]
This repo is so new and undocumented that everyone (except us here at card.io/PayPal) is a newbie! So creating issues is a good way to provide help to the next newbie. :smiley_cat:

**Comment by burnto** [comment]
Maybe a parallel google group for such discussion is in order?

On Tuesday, January 13, 2015, Dave Goldman <notifications@github.com> wrote:

> This repo is so new and undocumented that everyone (except us here at
> card.io/PayPal) is a newbie! So creating issues is a good way to provide
> help to the next newbie. [image: :smiley_cat:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/card-io/card.io-iOS-source/issues/9#issuecomment-69848277>
> .
>


--

**Comment by dgoldman-ebay** [comment]
@burnto so far I'm okay with using github issues, so that everything is one place. But would there be advantages to a google group?

**Comment by burnto** [comment]
Eventually, if enough folks are using the source code, it might provide
some value for open discussion. Yeah I agree GitHub is ok for now. :)

On Tuesday, January 13, 2015, Dave Goldman <notifications@github.com> wrote:

> @burnto <https://github.com/burnto> so far I'm okay with using github
> issues, so that everything is one place. But would there be advantages to a
> google group?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/card-io/card.io-iOS-source/issues/9#issuecomment-69880021>
> .
>


--

**Comment by ricardolpd** [comment]
@burnto @dgoldman-ebay i wasn't aware that this is a small comunity as i just downloaded the project yesterday. Which was why i raised the question. 
But yes if the community grows bigger a place like google groups would be better, so you guys don't get fake issues being brought over all the time. Thanks for your help guys.

**Comment by burnto** [comment]
@ricardolpd - yep card.io is pretty widely used as a [library](https://github.com/card-io/card.io-iOS-SDK), but this open source project is very new still, and it's not yet clear how many folks will be interested in it!

We'd love to hear what you're doing with the code! :smile:

**Comment by ricardolpd** [comment]
@burnto yeah, i noticed that, i prefer myself to use source, always gives a chance to learn new things.

Unfortunately my contract doesn't allow me to talk about work, i can just tell u that i work for a financial company in but it wouldn't be hard to find out to whom:).
